# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mv_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_mv_set(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 250)
        Dialog.setStyleSheet("QDialog {\n"
"    border: 2px solid #f0f8ff; /* 设置对话框的边框颜色 */\n"
"    border-radius: 10px; /* 设置对话框的圆角 */\n"
"background-color: white;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 200, 341, 32))
        self.buttonBox.setStyleSheet("QDialogButtonBox {\n"
"    background-color: white; /* 设置按钮盒的背景颜色 */\n"
"    border: 1px solid #cccccc; /* 设置按钮盒的边框颜色 */\n"
"    border-radius: 5px; /* 设置按钮盒的圆角 */\n"
"    padding: 5px; /* 设置按钮盒的内边距 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #4CAF50; /* 设置按钮的背景颜色 */\n"
" background-color: white; /* 设置按钮的背景颜色 */\n"
"    color: balck; /* 设置按钮的文本颜色 */\n"
"    border: 2px solid black;; /* 去掉按钮的边框 */\n"
"    border-radius: 5px; /* 设置按钮的圆角 */\n"
"    padding: 5px 10px; /* 设置按钮的内边距 */\n"
"    font-size: 14px; /* 设置按钮的字体大小 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:hover {\n"
"    background-color: #CCCCCC; /* 设置按钮鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:pressed {\n"
"    background-color: #999999; /* 设置按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:disabled {\n"
"    background-color: #666666; /* 设置按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 设置按钮禁用时的文本颜色} */\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.doubleSpinBox_time = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_time.setGeometry(QtCore.QRect(180, 60, 80, 30))
        self.doubleSpinBox_time.setStyleSheet("")
        self.doubleSpinBox_time.setObjectName("doubleSpinBox_time")
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_height.setGeometry(QtCore.QRect(180, 130, 80, 30))
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.label_mode = QtWidgets.QLabel(Dialog)
        self.label_mode.setGeometry(QtCore.QRect(50, 60, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.label_mode_2 = QtWidgets.QLabel(Dialog)
        self.label_mode_2.setGeometry(QtCore.QRect(50, 130, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_mode_2.setFont(font)
        self.label_mode_2.setObjectName("label_mode_2")
        self.label_mode_2.raise_()
        self.label_mode.raise_()
        self.buttonBox.raise_()
        self.doubleSpinBox_time.raise_()
        self.doubleSpinBox_height.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "动作设置窗口"))
        self.label_mode.setText(_translate("Dialog", "点胶时间：                         s"))
        self.label_mode_2.setText(_translate("Dialog", "胶头高度：                         mm"))
