# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painter_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_painter_set(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 250)
        Dialog.setStyleSheet("QDialog {\n"
"    border: 2px solid #f0f8ff; /* 设置对话框的边框颜色 */\n"
"    border-radius: 10px; /* 设置对话框的圆角 */\n"
"background-color: white;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 201, 341, 41))
        self.buttonBox.setStyleSheet("QDialogButtonBox {\n"
"    background-color: #white; /* 设置按钮盒的背景颜色 */\n"
"    border: 1px solid #cccccc; /* 设置按钮盒的边框颜色 */\n"
"    border-radius: 5px; /* 设置按钮盒的圆角 */\n"
"    padding: 5px; /* 设置按钮盒的内边距 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #4CAF50; /* 设置按钮的背景颜色 */\n"
" background-color: white; /* 设置按钮的背景颜色 */\n"
"    color: balck; /* 设置按钮的文本颜色 */\n"
"    border: 2px solid black;; /* 去掉按钮的边框 */\n"
"    border-radius: 5px; /* 设置按钮的圆角 */\n"
"    padding: 5px 10px; /* 设置按钮的内边距 */\n"
"    font-size: 14px; /* 设置按钮的字体大小 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:hover {\n"
"    background-color: #CCCCCC; /* 设置按钮鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:pressed {\n"
"    background-color: #999999; /* 设置按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:disabled {\n"
"    background-color: #666666; /* 设置按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 设置按钮禁用时的文本颜色} */\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(200, 50, 80, 30))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid black; /* 浅蓝色边框 */\n"
"    border-radius: 5px; /* 圆角 */\n"
"    padding: 5px; /* 内边距 */\n"
"    selection-background-color: #999999; /* 选中时的背景色 */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"   // background-color: #cccccc; /* 下拉箭头的背景色 */\n"
"    border-left: 1px solid #b2dfdb; /* 左边框 */\n"
"    border-right: 1px solid #b2dfdb; /* 左边框 */\n"
"    border-radius: 5px 5px 5px 5px; /* 圆角 */\n"
"    width: 10px; /* 箭头宽度 */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_mode = QtWidgets.QLabel(Dialog)
        self.label_mode.setGeometry(QtCore.QRect(80, 50, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.labelPointColor = QtWidgets.QLabel(Dialog)
        self.labelPointColor.setGeometry(QtCore.QRect(80, 100, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPointColor.setFont(font)
        self.labelPointColor.setObjectName("labelPointColor")
        self.button_PointColor = QtWidgets.QPushButton(Dialog)
        self.button_PointColor.setGeometry(QtCore.QRect(200, 100, 80, 30))
        self.button_PointColor.setStyleSheet("QPushButton {\n"
"border: 1px solid black; /* 浅蓝色边框 */\n"
"border-radius: 5px; /* 圆角 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #cccccc; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #999999; /* 按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666; /* 按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 按钮禁用时的文本颜色 */\n"
"    border: 1px solid #aaaaaa; /* 按钮禁用时的边框颜色 */\n"
"}")
        self.button_PointColor.setObjectName("button_PointColor")
        self.labelLineColor = QtWidgets.QLabel(Dialog)
        self.labelLineColor.setGeometry(QtCore.QRect(80, 150, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelLineColor.setFont(font)
        self.labelLineColor.setObjectName("labelLineColor")
        self.button_LineColor = QtWidgets.QPushButton(Dialog)
        self.button_LineColor.setGeometry(QtCore.QRect(200, 150, 80, 30))
        self.button_LineColor.setStyleSheet("QPushButton {\n"
"border: 1px solid black; /* 浅蓝色边框 */\n"
"border-radius: 5px; /* 圆角 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #cccccc; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #999999; /* 按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666; /* 按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 按钮禁用时的文本颜色 */\n"
"    border: 1px solid #aaaaaa; /* 按钮禁用时的边框颜色 */\n"
"}")
        self.button_LineColor.setObjectName("button_LineColor")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "动作绘制选择窗口"))
        self.comboBox.setItemText(0, _translate("Dialog", "Point"))
        self.comboBox.setItemText(1, _translate("Dialog", "Line"))
        self.comboBox.setItemText(2, _translate("Dialog", "Circle"))
        self.label_mode.setText(_translate("Dialog", "动作模式："))
        self.labelPointColor.setText(_translate("Dialog", "“点”颜色："))
        self.button_PointColor.setText(_translate("Dialog", "..."))
        self.labelLineColor.setText(_translate("Dialog", "“线”颜色："))
        self.button_LineColor.setText(_translate("Dialog", "..."))
