# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter_reset.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_parameter_reset(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 180)
        Dialog.setStyleSheet("QDialog {\n"
"    border: 2px solid #f0f8ff; /* 设置对话框的边框颜色 */\n"
"    border-radius: 10px; /* 设置对话框的圆角 */\n"
"background-color: white;\n"
"}")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(190, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"    border: 1px solid black; /* 设置对话框的边框颜色 */\n"
"    border-radius: 5px; /* 设置对话框的圆角 */\n"
"background-color: white;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(70, 92, 251, 17))
        self.label_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_info.setObjectName("label_info")
        self.btn_accept = QtWidgets.QPushButton(Dialog)
        self.btn_accept.setGeometry(QtCore.QRect(300, 130, 90, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_accept.sizePolicy().hasHeightForWidth())
        self.btn_accept.setSizePolicy(sizePolicy)
        self.btn_accept.setStyleSheet("QPushButton {\n"
"border: 1px solid black; /* 浅蓝色边框 */\n"
"border-radius: 5px; /* 圆角 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #cccccc; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #999999; /* 按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666; /* 按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 按钮禁用时的文本颜色 */\n"
"    border: 1px solid #aaaaaa; /* 按钮禁用时的边框颜色 */\n"
"}")
        self.btn_accept.setObjectName("btn_accept")
        self.btn_reject = QtWidgets.QPushButton(Dialog)
        self.btn_reject.setGeometry(QtCore.QRect(200, 130, 90, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reject.sizePolicy().hasHeightForWidth())
        self.btn_reject.setSizePolicy(sizePolicy)
        self.btn_reject.setStyleSheet("QPushButton {\n"
"border: 1px solid black; /* 浅蓝色边框 */\n"
"border-radius: 5px; /* 圆角 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #cccccc; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #999999; /* 按钮按下时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666; /* 按钮禁用时的背景颜色 */\n"
"    color: #888888; /* 按钮禁用时的文本颜色 */\n"
"    border: 1px solid #aaaaaa; /* 按钮禁用时的边框颜色 */\n"
"}")
        self.btn_reject.setObjectName("btn_reject")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "点胶参数设置窗口"))
        self.label.setText(_translate("Dialog", "参数："))
        self.label_info.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\"><br/></span></p></body></html>"))
        self.btn_accept.setText(_translate("Dialog", "确认"))
        self.btn_reject.setText(_translate("Dialog", "取消"))
